version: 2.1
jobs:
  build:
    docker:
      - image: cimg/ruby:3.2.1
    steps:
      - checkout
      - run: bundle install
      - run: bundle exec rspec --color --require spec_helper spec --format progress
