version: 2.1
jobs:
  build:
    docker:
      - image: circleci/ruby:3.1.2
    steps:
      - checkout
      - run: bundle install
      - run: bundle exec rspec --color --require spec_helper spec --format progress
